grafana:
  enabled: false

alertmanager:
  enabled: false

prometheus:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - prometheus.127.0.0.1.nip.io
    paths:
      - /
  prometheusSpec:
    retention: 2d
    scrapeInterval: 15s
    evaluationInterval: 15s
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    podMonitorSelector: {}
    podMonitorNamespaceSelector: {}
    ruleSelector: {}
    ruleNamespaceSelector: {}
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
